[tool.mypy]
python_version = "3.12"
mypy_path = "stubs"
strict = true
packages = ["diagen", "test"]

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false

[tool.ruff.lint]
ignore = ["E731", "E402", "E743"]

[tool.coverage.run]
source = ["diagen"]

[tool.coverage.report]
omit = ["props-gen.py"]
